version: '2'

services:
  nginx:
    build: docker/nginx
    ports:
      - 92:80
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
  php:
    build:
      context: docker/php7-fpm
      args:
        TIMEZONE: Europe/London
    shm_size: '2gb'
    volumes:
      - ./:/var/www/symfony
      - ./.composer:/root/.composer/:cached
      - ./logs/symfony:/var/www/symfony/app/logs
  nodejs:
    build:
      context: docker/nodejs
    ports:
      - 3002:3000
    volumes:
      - ./:/var/www/symfony
  memcached:
    image: memcached
    ports:
      - 11233:11211
  db:
    image: mysql:5
    ports:
      - 3338:3306
    volumes:
      - "mysql-test:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
  mailhog:
    build: docker/mailhog
    ports:
      - 1057:1025
      - 8057:8025
volumes:
  mysql-test: